memory_limit = 756M
opcache.enable                 = 1
opcache.enable_cli             = 1
opcache.memory_consumption     = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files  = 60000
opcache.revalidate_freq        = 0
opcache.validate_timestamps    = 0
opcache.save_comments          = 1
opcache.fast_shutdown          = 1
max_execution_time  = 1800
max_input_time      = 1800
max_input_vars      = 10000
upload_max_filesize = 64M
post_max_size       = 64M
session.gc_maxlifetime = 86400
display_errors         = Off
log_errors             = On
error_log              = /proc/self/fd/2
date.timezone = UTC
realpath_cache_size = 10M
realpath_cache_ttl  = 7200

; CLI memory limit for cron

; CLI override - needed for cron
